### ISSUE TITLE
Custom maps don't see layers defined via hook_leaflet_map_info()

### ISSUE THREAD

**Issue by AlexHoebart-ICPDR** [backdrop-contrib/leaflet#27]
Custom maps which can be defined in the Leaflet More Maps settings, do not see additional layers defined via hook_leaflet_map_info()
This worked in the Drupal7 version, some original code is missing or is in the wrong hook. Will add a PR.

**Comment by indigoxela** [comment]
@AlexHoebart-ICPDR many thanks for reporting. Will have a closer look ASAP.

**Comment by indigoxela** [comment]
I took a look now. Honestly, at first I found the switch from leaflet_more_maps_leaflet_map_info to leaflet_more_maps_leaflet_map_info_alter a bit irritating, but then I realized the problem with overlaps (recursion) that would otherwise pop up.

Tested your changes locally, also with a custom module implementing that hook (but osm mapnik earth also wasn't available before). This all works like a charm, many thanks for contributing!
